### ISSUE TITLE
Fails to compile with rustc 1.34.2 due to using ".copied"

### ISSUE THREAD

**Issue by ecm-pushbx** [mookid/diffr#53]
On an older server running Debian 9 with rustc 1.34.2, pulling the latest git commit and building it fails with the error `error[E0658]: use of unstable library feature 'iter_copied' (see issue #57127)` due to the change in https://github.com/mookid/diffr/commit/9666edc502c44f2b0d794c6c2cb3af5fa3fe0fb7

I was able to patch the source to undo that change, leading to it successfully building. I used the following command:

```
perl -i -pe 's/\.copied/.cloned/g' diffr-lib/src/lib.rs diffr-lib/src/test.rs src/main.rs
```

Why was this change made? Is it needed? I don't know rust at all.

**Comment by mookid** [comment]
Thanks for the report. You can then revert the last commit that introduces these changes without functional change.

The change is more cosmetic than anything else.
